version: "3.9"
services:
  
  app1:
    build:
      context: ./microapps/app1
    ports:
      - "8081:80"
    networks:
      - app

  app2:
    build:
      context: ./microapps/app2
    ports:
      - "8082:80"
    networks:
      - app

  manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '8180:80'
      - '8181:81'
      - '8443:443'
    networks:
      - app
      
networks:
  app: