apiVersion: v1
kind: Service
metadata:
  name: proxy-manager
spec:
  type: LoadBalancer
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
    - name: "81"
      port: 81
      targetPort: 81
status:
  loadBalancer: {}
