apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: npm
            - name: MYSQL_PASSWORD
              value: npm
            - name: MYSQL_ROOT_PASSWORD
              value: npm
            - name: MYSQL_USER
              value: npm
          image: jc21/mariadb-aria:latest
          name: mariadb
          resources: {}
     
status: {}
